### ISSUE TITLE
Custom Indicators Regression

### ISSUE THREAD

**Issue by thebadking** [tradex-app/TradeX-chart#46]
Adding custom indicators on 0.140.2 is not possible anymore, was working up until 0.139.9

<img width="954" alt="image" src="https://github.com/tradex-app/TradeX-chart/assets/53491595/0f130f60-75c0-449b-b2a5-674dfa1915db">

**Comment by tradex-app** [comment]
Cannot reproduce this on the current `dev` branch, due to it failing to run.
![image](https://github.com/tradex-app/TradeX-chart/assets/108627597/20a083aa-bb00-43fd-bbf1-d4067d329fb9)

**Comment by tradex-app** [comment]
Cannot reproduce this on the current `dev` branch, due to it failing to run.

**Comment by tradex-app** [comment]
Fixed / working in Version [0.140.3](https://www.npmjs.com/package/tradex-chart/v/0.140.3)
