### ISSUE TITLE
gap between chart pane and axes

### ISSUE THREAD

**Issue by wmahmood1984** [tradex-app/TradeX-chart#64]
Hi, i am seeing a big gap between the chart pane (where actual candlesticks are there) and the x and y axes. 

I can remove this manually by modifiying the width and height of canvas element in console but cant rectify it in the file. Can someone please help me? 

![image](https://github.com/tradex-app/TradeX-chart/assets/56361582/088da042-9bbf-4142-b869-84cdecf39a0d)

**Comment by tradex-app** [comment]
Please provide a live example or a repo where this bug occurs.
Any other information on how to reproduce the bug would be good.

**Comment by wmahmood1984** [comment]
https://github.com/wmahmood1984/goatLaunch2 this is the repo

**Comment by wmahmood1984** [comment]
Please let me know if you need any further information

**Comment by tradex-app** [comment]
> https://github.com/wmahmood1984/goatLaunch2 this is the repo

@wmahmood1984 I have attempted to access the repo at that link, but there is nothing there.

**Comment by wmahmood1984** [comment]
Hi, i have made this repo public now. now you can see this

**Comment by tradex-app** [comment]
@wmahmood1984 thank you, I cloned the repository, installed the required libs.
But when I ran it, I did not see the chart or understand where to find it.

I did however see the same thing happening when I looked at the chart on my laptop, which was running old browser versions.

I upgraded my browsers.

FF - works
Chrome . different, but similar issue
Opera - works

These are all Linux versions. When I'm back at my main computer I will test on Windows.

Please inform me as to what browser you are using.

**Comment by tradex-app** [comment]
This issue has now been resolved with the following commit:
[34e7afb27ea1b1d8c8c8d7b66f07d19cd542f227](https://github.com/tradex-app/TradeX-chart/commit/34e7afb27ea1b1d8c8c8d7b66f07d19cd542f227)
