### ISSUE TITLE
Discord invite link is disabled?

### ISSUE THREAD

**Issue by luketych** [tradex-app/TradeX-chart#86]
Is the discord still running?

**Comment by tradex-app** [comment]
Yes, here's another link:
https://discord.gg/6XS9tDrcdq

**Comment by tradex-app** [comment]
Yes, here's another link:
https://discord.gg/ZcsUsWP4
Link expires in seven days.

**Comment by tradex-app** [comment]
@luketych
Yes, here's another link:
https://discord.gg/ZcsUsWP4
Link expires in seven days

And the docs (WIP):
https://tradex-app.github.io/TradeX-chart/
